services:
  mlflow-server:
    image: python:3.11-slim
    container_name: mlflow-server
    working_dir: /mlflow
    command: >
      bash -c "
      pip install mlflow==2.12.2 &&
      mlflow server
      --host 0.0.0.0
      --port 5000
      --backend-store-uri file:///mlflow/mlruns
      --default-artifact-root file:///mlflow/mlruns
      "
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    networks:
      - mlops-network

  api-service:
    build: .
    ports:
      - "8000-8002:8000"
    depends_on:
      - mlflow-server
    deploy:
      replicas: 3
    networks:
      - mlops-network
    volumes:
      - .:/app
      - ./mlruns:/workspaces/MLOps-Prediksi-Harga-Bitcoin/mlruns

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus.rules.yml:/etc/prometheus/prometheus.rules.yml # <-- UPDATE: Hubungkan file rules
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    depends_on:
      - api-service
    networks:
      - mlops-network

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml # <-- BARU: Hubungkan file alertmanager
    networks:
      - mlops-network

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
      - alertmanager # <-- UPDATE: Grafana nunggu alertmanager siap juga
    networks:
      - mlops-network

networks:
  mlops-network:
    driver: bridge