name: MLOps Automation Pipeline

on:
  push:
    branches:
      - main
      - feat/initial-setup
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools==69.5.1 wheel
        pip install -r requirements.txt

    - name: Pull DVC Data
      run: |
        dvc pull

    - name: Generate Dataset
      run: | 
        python src/preprocess.py

    - name: Run Unit Test
      run: |
        pytest tests/

  train:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools==69.5.1 wheel
        pip install dvc
        pip install -r requirements.txt

    # 🛠️ TRIK UTAMA: Bikin folder tipuan biar MLflow gak Error Permission Denied!
    - name: Create Workspaces Directory for MLflow
      run: |
        sudo mkdir -p /workspaces/MLOps-Prediksi-Harga-Bitcoin
        sudo chmod -R 777 /workspaces

    - name: Pull DVC Data
      run: |
        dvc pull

    - name: Generate Dataset
      run: |
        python src/preprocess.py

    - name: Run Training
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      run: |
        python src/train_best.py

  evaluate:
    needs: train
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools==69.5.1 wheel
        pip install -r requirements.txt

    - name: Evaluate Model
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      run: |
        python src/evaluate.py

    - name: Upload Run ID Artifact
      uses: actions/upload-artifact@v4
      with:
        name: run-id-artifact
        path: latest_run_id.txt

  registry:
    needs: evaluate
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install Dependencies
      run: |
        pip install --upgrade pip
        pip install setuptools==69.5.1 wheel
        pip install -r requirements.txt

    - name: Download Run ID Artifact
      uses: actions/download-artifact@v4
      with:
        name: run-id-artifact

    - name: Run Registry Step
      env:
        MLFLOW_TRACKING_URI: ${{ secrets.MLFLOW_TRACKING_URI }}
      run: |
        python src/register.py